### ISSUE TITLE
Unit tests assert undesirable behavior

### ISSUE THREAD

**Issue by japem** [kubernetes-sigs/yaml#111]
Many unit tests in this library assert results that seem less than ideal. As just one example ([permalink](https://github.com/kubernetes-sigs/yaml/blob/c3772b51db126345efe2dfe4ff8dac83b8141684/yaml_test.go#L301)):

```go
"tagged non-casematched boolean key (yes)": {
	encoded:    []byte("yes: test"),
	decodeInto: new(UnmarshalTaggedStruct),
	decoded:    UnmarshalTaggedStruct{TrueLower: "test"},
},
```

This asserts that the `yes` field is unmarshaled into the `TrueLower` property of the struct, which has a JSON tag of `"true"`. However, there is another field (`YesLower`) that has a JSON tag of `"yes"`.

Clearly, this behavior does not seem ideal. However, because there is a unit test asserting this case, I'm not sure whether code that uses this library (specifically core Kubernetes code such as kubectl) expects this case to work like this. If it doesn't, these tests should be removed, since it overstates the guarantees of this library and removes the possibility to fix this in the future without potentially breaking existing consumers.

I am forking this library for my own purposes, and the changes I have made break this case by unmarshaling this field instead into `YesLower`. (I've also broken several other similarly undesirable-seeming cases.) I would like to know if it's ok for me to use my code anyways to parse Kubernetes resource YAML files. I expect it should be, but I can't be sure.

**Comment by liggitt** [comment]
I 100% agree that `yes` being interpreted as `true` is less than ideal, but the yaml spec and the lack of a clear statement of whether go-yaml supported yaml 1.1 or 1.2 is the primary source of this pain. 

See more details in https://github.com/go-yaml/yaml/issues/283 / https://github.com/go-yaml/yaml/issues/214 / https://github.com/kubernetes/kubernetes/issues/34146

The unit test is here so that we don't accidentally change behavior without considering how to do so in a non-breaking way.

**Comment by japem** [comment]
Interesting, thanks for the references. Closing.

Looking through the differences between this library and YAML 1.2, it doesn't seem like using YAML 1.2 to parse Kubernetes resources using the existing Go structs, then re-marshaling to YAML (to eventually pass into Kubectl) would cause problems. Does that sound right?
