### ISSUE TITLE
At `"sigs.k8s.io/yaml/goyaml.v2"`, marshal output is incorrect when the string field is long and contains Colon and Space(`: `)

### ISSUE THREAD

**Issue by koba1t** [kubernetes-sigs/yaml#116]
### What happened?

The marshal output is incorrect when the string field is long and contains Colon and Space(`: `) at `"sigs.k8s.io/yaml/goyaml.v2"` pkg.

#### code
https://go.dev/play/p/WDmfH-PWqtW

```go
package main

import (
	"fmt"
	"log"

	yaml "sigs.k8s.io/yaml/goyaml.v2"
)

type StructA struct {
	A string `yaml:"a"`
}

var data = `
a: "12345678901234: .s"
`

var failedData = `
a: "12345678901234567890123456789012345678901234567890123456789012341234567890123456789012345678901234567890123456789012345678901234: .s"
`

func processYAML(input string) {
	var a StructA
	if err := yaml.Unmarshal([]byte(input), &a); err != nil {
		log.Printf("cannot unmarshal data: %v", err)
		return
	}

	yamlBytes, err := yaml.Marshal(a)
	if err != nil {
		log.Printf("cannot marshal data: %v", err)
		return
	}

	fmt.Println(string(yamlBytes))
}

func main() {
	processYAML(data)
	processYAML(failedData)
}
```

#### output
```
a: '12345678901234: .s'

a: '12345678901234567890123456789012345678901234567890123456789012341234567890123456789012345678901234567890123456789012345678901234:
  .s'
```

### Additionally
related to  https://github.com/kubernetes-sigs/kustomize/issues/947

**Comment by liggitt** [comment]
it's not clear to me that the resulting yaml is invalid... it round-trips correctly when unmarshaled, and other yaml linters validate it and appear to treat it correctly

see https://go.dev/play/p/_v1ZSI-MnM3

**Comment by koba1t** [comment]
Sorry, I didn't know about 'line folding' in the YAML specification.
https://yaml.org/spec/1.2.2/#65-line-folding

I mistakenly thought it looked like an unexpected extra line break had been added.
```yaml
a: '12345678901234567890123456789012345678901234567890123456789012341234567890123456789012345678901234567890123456789012345678901234:
  .s'
```

/close

**Comment by r10r** [comment]
@liggitt Do you mind to reopen this issue ?

I'm facing the same issue and according to https://github.com/go-yaml/yaml/pull/455#issuecomment-624939185
folding should already have been disabled in goyaml.v2. But it has not.

The YAML output becomes difficult to read and edit due to the line wrapping.
So it should be at least possible to disable the line wrapping in the encoder.
This should be fairly easy looking at the following pull requests:

- https://github.com/go-yaml/yaml/pull/670
- https://github.com/go-yaml/yaml/pull/455
- https://github.com/go-yaml/yaml/pull/329

What about merging https://github.com/go-yaml/yaml/pull/329 into the fork of goyaml.v2 ?

**Comment by liggitt** [comment]
We won't reopen _this_ specific issue, since the output is not actually incorrect.

Given that changing the line wrapping default in go-yaml broke things, and they had to back that change out, I'm not inclined to import that problem to this repo. More configurability / options in yaml output wouldn't help users of things like kubectl / kustomize, which would continue to keep compatible defaults using current wrapping behavior.

**Comment by r10r** [comment]
Thanks for the explanation. I think about creating a fork, but I wonder if this is a good idea. Do you know what exactly breaks when the maximum line width is changed? I'm fine with increasing the maximum line to a fixed width, let's say 200 chars. Will this generate invalid yaml ?

**Comment by liggitt** [comment]
> Do you know what exactly breaks when the maximum line width is changed?

For kubectl / kustomize users, anything expecting stable (byte-equivalent) output in yaml format release-to-release. It's still semantically equal, but was not byte-equal
