### ISSUE TITLE
Difference with gopkg.in/yaml.v2 for string like numeric parsing

### ISSUE THREAD

**Issue by llamerada-jp** [kubernetes-sigs/yaml#27]
I had noticed that a difference between this library and gopkg.in/yaml.v2 when parsing string like numeric.
It is a sample code and output of it below.
Could you fix it to get the same result?

code:
```go
package main

import (
	"fmt"

	yaml2 "gopkg.in/yaml.v2"
	"sigs.k8s.io/yaml"
)

type testStruct struct {
	Serial string `json:"serial,omitempty"`
}

var strYaml string = `
serial: 00000002
`

func main() {
	fmt.Println("sigs.k8s.io/yaml")

	str := []byte(strYaml)
	var c1 testStruct
	err := yaml.Unmarshal(str, &c1)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(c1)

	fmt.Println("gopkg.in/yaml.v2")
	var c2 testStruct
	err = yaml2.Unmarshal(str, &c2)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(c2)
}
```

output:

```
sigs.k8s.io/yaml
{2}
gopkg.in/yaml.v2
{00000002}
```

**Comment by nikhita** [comment]
This is actually a bug that comes from https://github.com/ghodss/yaml.

This occurs because while using `gopkg.in/yaml.v2`, we directly use `yaml2.Unmarshal` onto the struct, so the `reflect.Value` is correctly interpreted as `String`. When yaml2 sees that the value is string, it directly sets the value as string and doesn't do any extra normalizations on it:

https://github.com/go-yaml/yaml/blob/f221b8435cfb71e54062f6c6e99e9ade30b124d5/decode.go#L464


However, while using `sigs.k8s.io/yaml`/`github.com/ghodss/yaml`, we use the marshal func on an interface:

https://github.com/kubernetes-sigs/yaml/blob/4cd0c284b15f1735b8cc247df097d262b8903f9f/yaml.go#L123-L124

so the `reflect.Value` is interpreted as `Interface` and using `reflect.ValueOf(resolved)` below sets the value as `2`, instead of `00000002`.

https://github.com/go-yaml/yaml/blob/f221b8435cfb71e54062f6c6e99e9ade30b124d5/decode.go#L478

**Comment by dims** [comment]
another interesting note adding `"` seems to get the desired result ( https://play.golang.org/p/08dHoKvvR9M )

```
var strYaml string = `
serial: "00000002"
`
```

**Comment by llamerada-jp** [comment]
Thank you for your reply.
I tried to make a patch, but I realized it wasn't easy.
I will try the method taught by dims.
