### ISSUE TITLE
Marshal doesn't respect struct tags?

### ISSUE THREAD

**Issue by StarpTech** [kubernetes-sigs/yaml#38]
Hi, when reading the docs I thought that this library is a drop-in replacement for the `go-yaml` with the benefit that we don't need to maintain multiple tags and marshalers. I faced with the following issues when using `yaml.Marshal`

- Property keys with the name "on" are parsed as boolean even if a struct tag `json:"on"` exists.
- Empty values aren't omitted when using `json:"omitempty"`
- The order of my fields in the resulting YAML is broken.

From my understanding, all information gets lost [here](https://github.com/kubernetes-sigs/yaml/blob/06fcaf684a24cafc90ba149f5ad26d4fd759fbfb/yaml.go#L22). How do you deal with that?

**Comment by neolit123** [comment]
hi, could you share an example Go struct that reproduces all the problems or use the [Go playground](https://play.golang.org/)?

> Property keys with the name "on" are parsed as boolean even if a struct tag json:"name:on" exists.

what is the significance of the `:on` suffix in the name?
AFAIK, "name:on" would be treated as the whole name of the field.

> Empty values aren't omitted when using json:"omitempty"

https://play.golang.org/p/8QQpksNcdUf

this example shows that the output is

```
b: foo
```

instead of:
```
b: foo
c: ""
```

> The order of my fields in the resulting YAML is broken.

the resulted yaml fields are sorted alpha-numerically.

**Comment by StarpTech** [comment]
> what is the significance of the :on suffix in the name?

Sry that was a typo. I will try to provide examples.
