### ISSUE TITLE
Related Vulnerabilities fixes

### ISSUE THREAD

**Issue by sabuhigr** [kubernetes-sigs/yaml#95]
Hi all, while testing package vulnerabilities I saw below issues:

=== Module dependency that show where its coming ===
```
sabuhigr:home/sabuhigr$ go mod graph | grep sigs
github.com/swaggo/swag@v1.16.1 sigs.k8s.io/yaml@v1.3.0
```

Vulnerabilitiy 1:
`sigs.k8s.io/yaml:1.3.0 | Reference: CVE-2022-3064 | CVSS Score: 7.5 | Category: CWE-400 | Parsing malicious or large YAML documents can consume excessive amounts of CPU or memory.`

Vulnerability 2:
`Reference: CVE-2023-2251 | CVSS Score: 7.5 | Category: CWE-248 | Uncaught Exception in GitHub repository eemeli/yaml prior to 2.0.0-5.`

**Comment by liggitt** [comment]
v1.3.0 of this library includes gopkg.in/yaml.v2@v2.4.0: https://github.com/kubernetes-sigs/yaml/blob/v1.3.0/go.mod#L7)

That includes the fix for CVE-2022-3064 which was released in gopkg.in/yaml.v2@v2.2.4 (https://github.com/advisories/GHSA-6q6q-88xp-6f2r)

CVE-2023-2251 is for eemeli/yaml which is not used in this repo

/close
